server:
  port: 80
  context-path: /
# 拦截器  进入mvc的规则  意思是要在请求前加/**
  servlet-path: /
  
mybatis:  config-location: classpath:config/mybatis-config.xml
  mapper-locations:  - classpath:mapper/*.xml

  
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp#  datasource:#    url: jdbc:mysql://localhost:3306/social_shopping?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: 
#    driverClassName: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
    
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

logging:
  level: 
    org.apache.log4j.ConsoleAppender: debug
#    root: debug
  pattern:
    console: -->[%thread] %-5level %logger- %msg%n 
    














   