server:
  port: 8070
  context-path: /
# 拦截器  进入mvc的规则  意思是要在请求前加/**
  servlet-path: /
  
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations:
  - classpath:mapper/*.xml


spring:
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
      exclude: WEB-INF/**
  mvc:
    static-path-pattern: /**
    view:
      prefix: /pages/
#      suffix: .jsp
#  datasource:
#    url: jdbc:mysql://localhost:3306/social_shopping?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: 
#    driverClassName: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#  resources:
#    static-locations: 
#    - classpath:/public/
  thymeleaf:
    cache: false
    enabled: false
  messages:
    encoding: UTF-8
    basename: i18n/messages
#    cache-seconds: -1

logging:
  level: 
    org.apache.log4j.ConsoleAppender: debug
#    root: debug
  pattern:
    console: -->[%thread] %-5level %logger- %msg%n 
    














   